### PR TITLE
Fix dependencies for Kodi 19 rc 1

### PR DESCRIPTION
**Pull request by GraelHarsh**
Just minimal adaptions to allow the plugin to install (and run) under Kodi 19 rc 1 (Matrix)

Yatse interactions are working fine too, even from bandcamp android app.

Thanks for this nice plugin !

### CODE REVIEW

**Comment by Virusmater** [comment]
Thx for PR. Will merge it and push to the kodi repo once Kodi 19 will be released.

**Comment by GraelHarsh** [comment]
Perfect, thanks again !

**Comment by GraelHarsh** [comment]
Still working fine with fresh Kodi 19.0 Final release
https://github.com/xbmc/xbmc/releases/tag/19.0-Matrix
Cheers !

**Comment by Virusmater** [comment]
Added PR to the official repo:
https://github.com/xbmc/repo-plugins/pull/3377

**Pull request merged**
